"""empty message

Revision ID: c91659a3e357
Revises: 193c272745bc
Create Date: 2021-06-02 14:57:30.760681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91659a3e357'
down_revision = '193c272745bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('stoptime', sa.DateTime(), nullable=True),
    sa.Column('bikeid', sa.Integer(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('from_station_name', sa.String(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_name', sa.String(), nullable=True),
    sa.Column('usertype', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('trip_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_trip_bikeid'), 'trip', ['bikeid'], unique=False)
    op.create_index(op.f('ix_trip_birthday'), 'trip', ['birthday'], unique=False)
    op.create_index(op.f('ix_trip_from_station_id'), 'trip', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_trip_from_station_name'), 'trip', ['from_station_name'], unique=False)
    op.create_index(op.f('ix_trip_gender'), 'trip', ['gender'], unique=False)
    op.create_index(op.f('ix_trip_starttime'), 'trip', ['starttime'], unique=False)
    op.create_index(op.f('ix_trip_stoptime'), 'trip', ['stoptime'], unique=False)
    op.create_index(op.f('ix_trip_to_station_id'), 'trip', ['to_station_id'], unique=False)
    op.create_index(op.f('ix_trip_to_station_name'), 'trip', ['to_station_name'], unique=False)
    op.create_index(op.f('ix_trip_trip_duration'), 'trip', ['trip_duration'], unique=False)
    op.create_index(op.f('ix_trip_trip_id'), 'trip', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_usertype'), 'trip', ['usertype'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_usertype'), table_name='trip')
    op.drop_index(op.f('ix_trip_trip_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_trip_duration'), table_name='trip')
    op.drop_index(op.f('ix_trip_to_station_name'), table_name='trip')
    op.drop_index(op.f('ix_trip_to_station_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_stoptime'), table_name='trip')
    op.drop_index(op.f('ix_trip_starttime'), table_name='trip')
    op.drop_index(op.f('ix_trip_gender'), table_name='trip')
    op.drop_index(op.f('ix_trip_from_station_name'), table_name='trip')
    op.drop_index(op.f('ix_trip_from_station_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_birthday'), table_name='trip')
    op.drop_index(op.f('ix_trip_bikeid'), table_name='trip')
    op.drop_table('trip')
    # ### end Alembic commands ###
